name: YunTing
server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      url: jdbc:oracle:thin:@192.168.10.105:1521:orcl
      username: scott
      password: tiger
      initial-size: 10
      min-idle: 10
      max-wait: 60000
      max-active: 100
      validation-query: SELECT 1 FROM DUAL
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml






