name: YunTing
server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: scott
      password: tiger
      initial-size: 10
      min-idle: 10
      max-wait: 60000
      max-active: 100
      validation-query: SELECT 1 FROM DUAL
  ldap:
    embedded:
      ldif: ldap-server.ldif
      base-dn: dc=didispace,dc=com
    urls: ldap://localhost:1235
    base: dc=didispace,dc=com
    username: didispace
    password: 123456
mybatis:
  mapper-locations: classpath:com/sunware/example/mapper/*.xml
  config-location: classpath:mybatis.xml





